### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by buildersbrewery** [XenHat/SublimeLinter-contrib-lslint#1]
#### Referring to the README

Actually, if the only point in using the [makopo/sublime-text-lsl](https://github.com/makopo/sublime-text-lsl) package is to add the included binaries to one's PATH, then simply downloading them from [makopo/lslint](https://github.com/makopo/lslint) (more up-to-date than the original [pclewis/lslint](https://github.com/pclewis/lslint)) should do, too.

Anyway, you could add the files from [makopo/lslint](https://github.com/makopo/lslint) as a git module to this repo.

**Comment by XenHat** [comment]
The binaries are not the only point, as I do not provide the `lsl` and `ossl` file format/syntax definitions, in respect and hommage to the original work. Those definitions are somewhat required for the linter to function intuitively and the plugin was developed without the ambition of removing `lslint` as a dependency. I did not intent **SublimeLinter-contrib-lslint** to be a self-contained package, but only a supplement to makopo/lslint.

I may or may not provide a full-featured package later down the road, this has not been decided yet and little thinking has been done toward achieving this goal.

**Comment by buildersbrewery** [comment]
Fair enough.

**Comment by XenHat** [comment]
I edited my previous comment with further explanation. I will look into git modules, I wasn't aware of their existence.

**Comment by buildersbrewery** [comment]
Random example: [ajaxorg/ace](https://github.com/ajaxorg/ace)

References there:
- `./.gitmodules`
  - `./build`
  - `./doc/wiki`

**Comment by buildersbrewery** [comment]
Documentation:
- commands: https://git-scm.com/docs/git-submodule
- explanation: https://git-scm.com/docs/gitmodules
- tools and nice-to-know stuff: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by buildersbrewery** [comment]
#### Another idea

You could also copy only the binaries, readme and license of [makopo/lslint](https://github.com/makopo/lslint) to another repo and publish that repo as a [PackageControl dependency](https://packagecontrol.io/docs/dependencies), then add a `dependencies.json` file to the root of this repo:

``` json
{
    "*": {
        "*": [
            "lslint"
        ]
    }
}
```

See the `Examples` section on the linked page and compare that to your `./Data/Packages/` folder (which should include PackageControl's dependencies).

**Comment by XenHat** [comment]
A better solution in my eyes than the git subrepo, thank you for the suggestion. I'll see what I can do.

**Comment by XenHat** [comment]
Well the problem with any approach is that I can't seem to automatically configure the path for the binaries. Perhaps Sublime Text itself can see dependencies installed, but SublimeLinter seems incapable of doing so.

**Comment by buildersbrewery** [comment]
Yeah, sorry if my first post was messed up.

Users will still need to add the binaries to path **themselves** anyhow. I was only stating that you could shortcut the steps up until that last one, by including the binaries here or maybe trying the dependencies workaround.

**Comment by buildersbrewery** [comment]
Looking through the contribution packages of SublimeLinter I notice that none of them (couple I looked through in the last 10 mins) actually binaries or language grammar, completions, tooltips or what-not.

Maybe if you'd prefer sticking with the setup of those others, then leave it as it was? No binaries or other stuff included?

Whoever gets this far to use a sublimelinter add-on, can figure out the rest for sure. I'd probably stick to improving the README, now that I've seen the other ones.

Just my two cents, **keep up the great work**. I was gonna send a PR to update the README. But you're at it and I'll refrain from doing so and see where it goes.

---

P.S.: Maybe close this for now again?

**Comment by buildersbrewery** [comment]
If you need help, give a shout :+1:

**Comment by XenHat** [comment]
I don't really want to close this, I don't see a way to truly resolve this and it makes a good piece of conversation. I have hereby added the required label.

> Maybe if you'd prefer sticking with the setup of those others, then leave it as it was? No binaries or other stuff included?

I added the definitions in the package in case new users did not already have LSL language installed (such as users coming here from Second Life after learning that Sublime Text could do LSL compiling/linting). I would include the binaries as well but that is extra work and creating bloat if you have lslint already, so I made a lightweight package containing the binaries only.

I am pretty much done with the readme for now, feel free to give it a look again.

**Comment by buildersbrewery** [comment]
Problem with how it is now, is that you override anything users already have installed language wise.

**Comment by buildersbrewery** [comment]
@XenHat see #2 for proposed changes.

**Comment by buildersbrewery** [comment]
I could add something along the lines of

```python
import sys
sys.path.append("/this/is/some/random/path/to/lslint")
```

to reference the lslint dependency if you plan on further working on the binary only git repo you created yesterday. However that would require publishing it first via PackageControl dependencies.

**Comment by buildersbrewery** [comment]
Another dependencies example:
- I added tooltips via PR to Makopo/sublime-text-lsl#38.

---

Regarding this discussion, I believe we've come to a halt as of right now. Have nothing to add to the README.

**Comment by XenHat** [comment]
Okay. I look forward the completion of the tooltips feature.

**Comment by buildersbrewery** [comment]
#### Path configuration
- I believe one can add executable paths to PATH via Python temporarily (via `plugin_loaded()` and `plugin_unloaded()`).
- Users should be able to adjust settings for lslint path target.
  - `"path_is": "dependent"` or `"path_is": "custom"`
    - https://packagecontrol.io/docs/dependencies
  - `"path_custom_target": "path/to/where/lslint/is"`

#### Tooltips support

:warning: User experience differs in examples below.
- https://github.com/buildersbrewery/linden-scripting-language/tree/master/sublimetext
- https://github.com/Makopo/sublime-text-tooltip-lsl

**Comment by buildersbrewery** [comment]
Path issue solved by buildersbrewery/linden-scripting-language@cbc0e4a as far as I can tell. I still need to differentiate for Windows.

**Comment by XenHat** [comment]
I still struggle to find a way to keep myself updated with  buildersbrewery/linden-scripting-language since I cannot install it as a package, so my involvement is a little complicated at the moment. But good job finding how to do this 👍

**Comment by XenHat** [comment]
I haven't given up on this but I do not know where to pick up anymore. I would like to avoid having to install 8 packages just to script in sublime-text, but the buildersbrewery "package" isn't an actual "package" I can throw at a new sublime-text installation. Until this issue is solved, I cannot really do any work toward integrating more closely.
 Ideally I would want to have makopo/lslint as the binary kit, @buildersbrewery tooltips and syntax definitions, and this linter plugin to glue everything together.
I really do not have the time and energy to maintain a separate repository only combining these components, it would fall behind very quickly.

Is there a way we can coordinate everything in a one or two step installation plugin? I'm utterly lost.

**Comment by buildersbrewery** [comment]
A few thoughts regarding your questions:

* This repo's functionality could be merged into [makopo/sublime-text-lsl](https://github.com/makopo/sublime-text-lsl)
  * @Makopo is already including the `lslint` binaries from [makopo/lslint](https://github.com/makopo/lslint) within [makopo/sublime-text-lsl](https://github.com/makopo/sublime-text-lsl) so adding the SublimeLinter config file for `*.lsl` files with a reference to the package's binaries would suffice.
  * the `lslint` win32 and win64 binaries should be added though, too
    * use those as additional optional build system
    * use those for newer Windows
* The syntax definition re-write with the syntax tests for [Sublime Text 3](https://www.sublimetext.com/3) from [buildersbrewery/linden-scripting-language](https://github.com/buildersbrewery/linden-scripting-language) is currently not finished.
  * compare the `sublimetext/LSL/syntaxes` subfolder there
  * syntax tests from [makopo/lslint](https://github.com/makopo/lslint) should pass
  * I'm still looking for clean definitions in regard to Makopo/sublime-text-lsl#19 and the first comment on sublimehq/Packages#115
  * compare <https://www.sublimetext.com/docs/3/syntax.html>
  * compare <https://www.sublimetext.com/docs/3/syntax.html#testing>
  * compare <https://www.sublimetext.com/docs/3/scope_naming.html>
  * [Sublime Text 3](https://www.sublimetext.com/3) is still in beta
* Tooltips are depending upon [facelessuser/sublime-markdown-popups](https://github.com/facelessuser/sublime-markdown-popups) and triggered upon hover for [buildersbrewery/linden-scripting-language](https://github.com/buildersbrewery/linden-scripting-language)
  * `v2.0` release of md-popups is planned for June
  * [Sublime Text 3](https://www.sublimetext.com/3) is still in beta
  * should eventually be generated from @Sei-Lisa 's kwdb project (see: [bitbucket.org/Sei_Lisa/kwdb](https://bitbucket.org/Sei_Lisa/kwdb))
  * currently testing (compare screencast below) with integrated code snippets (while hovering over types and states)
  * @Makopo didn't want to include the tooltips in the LSL main package
    * he didn't want to have a dependency (on md-popups which I was using for the code snippets) or use hover
    * maybe we could fix this so that tooltips show next to completions only ❓❓
      * open to other suggestions
    * compare Makopo/sublime-text-lsl#34
    * compare Makopo/sublime-text-lsl#38

<br>

![screencast](https://cloud.githubusercontent.com/assets/13032004/25950371/0a5cf09c-365b-11e7-8bac-74313d4f1f31.gif)

**Comment by XenHat** [comment]
> This repo's functionality could be merged into makopo/sublime-text-lsl

Due to guidelines on how to name the SublimeLinter third party linters, I would still keep this standalone package, but I am not against adding it to makopo's package **if there is a way to check for SublimeLinter's presence to avoid cruft**

> the lslint win32 and win64 binaries should be added though, too

I agree. Rather active work is being done on the lslint code base with Sei's help, this will probably need to be completed, then heavily tested before adding to the main sublime-text-lsl package.

> The syntax definition re-write with the syntax tests for Sublime Text 3 from buildersbrewery/linden-scripting-language is currently not finished.

Very well. Sliding puzzles ahoy!

> adding the SublimeLinter config file for *.lsl files with a reference to the package's binaries would suffice.

I'm not familiar with the internals of sublime packages, if you know how, or where the documentation bits for this step are, I would like to know.

**Comment by buildersbrewery** [comment]
### SublimeLinter installer

<details>
<summary>SublimeLinter installer script (click here)</summary>

```python
'''
SublimeLinter Installer
'''

import os
import sublime

SUBL_LINTER_PKG = 'SublimeLinter'
PKGCTRL_SETTINGS = 'Package Control.sublime-settings'

PKG_NAME = os.path.splitext(
    os.path.basename(os.path.dirname(__file__))
)[0]

MSG = '''\
<div id="SublimeLinter-installer">
  <style>
    #SublimeLinter-installer {{
      padding: 1rem;
      line-height: 1.5;
    }}
    #SublimeLinter-installer code {{
      background-color: color(var(--background) blend(var(--foreground) 80%));
      line-height: 1;
      padding: 0.25rem;
    }}
    #SublimeLinter-installer a {{
      padding: 0;
      margin: 0;
    }}
  </style>

  {} requires <code>SublimeLinter</code> package.
  <br><br>Would you like to install it?<br>
  <br><a href="install">Install</a> <a href="cancel">Cancel</a>
</div>
'''.format(PKG_NAME)


def is_installed():
    pkgctrl_settings = sublime.load_settings(PKGCTRL_SETTINGS)

    return SUBL_LINTER_PKG in set(pkgctrl_settings.get('installed_packages', []))


def on_navigate(href):
    if href.startswith('install'):
        install()
    else:
        hide()


def install():
    print('Installing "{}" ...'.format(SUBL_LINTER_PKG))
    sublime.active_window().run_command(
        'advanced_install_package', {'packages': SUBL_LINTER_PKG}
    )
    hide()


def hide():
    sublime.active_window().active_view().hide_popup()


def plugin_loaded():
    from package_control import events

    if events.install(PKG_NAME) and not is_installed():
        window = sublime.active_window()
        view = window.active_view()
        window.focus_view(view)
        row = int(view.rowcol(view.visible_region().a)[0] + 1)
        view.show_popup(
            MSG,
            location=view.text_point(row, 5),
            max_width=800,
            max_height=800,
            on_navigate=on_navigate
        )
```

</details>

### Current state...

Have been updating a lot! Currently going through tooltips... check it out!

<https://github.com/buildersbrewery/linden-scripting-language/tree/master/sublimetext>

**Comment by XenHat** [comment]
@buildersbrewery H..How do I use this? :D Sorry I'm not that knowledgeable with Sublime-Text internals..

EDIT: For now I cloned bb/lsl into a folder and made a junction to the packages folder so that I can keep in sync more easily

So far I have noticed a problem since upgrading to the latest version of lslint.exe and bb/lsl:
**Linting stops at the first error, which is a problem with preprocessor directives**
is this something that changed?

**Comment by Sei-Lisa** [comment]
@XenHat Can you please try to produce an example of something that worked with an earlier version and no longer does, and submit it to the lslint issue tracker?

**Comment by XenHat** [comment]
@Sei-Lisa created! https://github.com/Makopo/lslint/issues/46
