### ISSUE TITLE
Multiline WARN messages from lslint cause an exception in linter.py

### ISSUE THREAD

**Issue by thickbrick** [XenHat/SublimeLinter-contrib-lslint#10]
### Offending code
```lsl
default {
    state_entry() {
        state default;
    }
}
```

## Linter output
This is the lslint output that's causing the problem:
```
WARN:: (  5,  9): Changing state to current state acts the same as return. (SL1.8.3)
                    If this is what you intended, consider using return instead.
```

The traceback I get in the console end in this:
```
File "linter in <snip>/SublimeLinter-contrib-lslint.sublime-package", line 269, in run
AttributeError: 'NoneType' object has no attribute 'group'
```

The second line from lslint is not matched by the regex on line 268 of linter.py, which causes `rres` to be `NoneType`.  Maybe check if `rres` exists and append `iter_line.strip()` to the last line in `fixed_output_lines` if it doesn't?

## My environment

* Operating system: `Linux (Debian 9.3)`
* Sublime Text Build `3143` on branch `stable`
* lslint version `1.0.8` from `release`
* SublimeLinter version `3.10.8`
* SublimeLinter-contrib-lslint version `1.4.0`

**Comment by XenHat** [comment]
oh wow, I've never encountered a multi-line error from lslint before. Nice catch! i will fix that as soon as i can.

**Comment by XenHat** [comment]
@thickbrick Does https://github.com/XenHat/SublimeLinter-contrib-lslint/blob/6674409782a32113e724a1b1e44967bcd5b43989/linter.py solve your issue?

**Comment by thickbrick** [comment]
Yes, that fixes it.
