### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by buildersbrewery** [XenHat/SublimeLinter-contrib-lslint#4]
- [x] add missing docstrings (⚠️ this should fix Travis)
- [x] mention changes from PR #3 in the README where `lslint` binaries from the LSL package are preferred
- [x]  update Package Control installation message with new instructions

**Comment by XenHat** [comment]
> update Package Control installation message with new instructions

I'm not quite sure what happens if the user accidentally dismisses the popup, I did it on accident and simply reinstalled the package.
